export interface InterestingType {
  value: number;
  label: string;
}

const INTERESTING_DATA = [
  {value: 1, label: '여행'},
  {value: 2, label: '영화/드라마'},
  {value: 3, label: '뮤지컬'},
  {value: 4, label: '음악'},
  {value: 4, label: '춤'},
  {value: 4, label: '독서'},
  {value: 4, label: '운동'},
  {value: 4, label: '요리'},
  {value: 4, label: '수영'},
  {value: 4, label: '헬스'},
  {value: 4, label: '야구'},
  {value: 4, label: '축구'},
  {value: 4, label: '농구'},
  {value: 4, label: '러닝'},
  {value: 4, label: '자전거'},
  {value: 4, label: '산책'},
  {value: 4, label: '애니'},
  {value: 4, label: '사진'},
  {value: 4, label: '악기연주'},
  {value: 4, label: '반려동물'},
  {value: 4, label: '보드게임'},
  {value: 4, label: '게임'},
  {value: 4, label: '취업준비'},
  {value: 4, label: '자격증'},
  {value: 4, label: '고민상담'},
  {value: 4, label: '맛집'},
  {value: 4, label: '시사/정치'},
  {value: 4, label: '외국어공부'},
  {value: 4, label: '제테크'},
  {value: 4, label: '덕질'},
  {value: 4, label: '메이크업'},
  {value: 4, label: '패션'},
  {value: 4, label: '다이어트'},
  {value: 4, label: '종교'},
];
